-- 013: Rename tables to align with Verify branding
-- Run in Supabase SQL Editor
-- Renames: match_candidates -> decision_candidates, steward_notes -> reviewer_notes
-- Column renames: steward -> reviewer in reviewer_notes

-- ============================================================
-- STEP 1: Rename tables
-- ============================================================
ALTER TABLE staging.match_candidates RENAME TO decision_candidates;
ALTER TABLE staging.steward_notes RENAME TO reviewer_notes;

-- ============================================================
-- STEP 2: Rename column in reviewer_notes
-- ============================================================
ALTER TABLE staging.reviewer_notes RENAME COLUMN steward TO reviewer;

-- ============================================================
-- STEP 3: Rename sequences (auto-generated by SERIAL)
-- ============================================================
ALTER SEQUENCE staging.match_candidates_pair_id_seq RENAME TO decision_candidates_pair_id_seq;
ALTER SEQUENCE staging.steward_notes_note_id_seq RENAME TO reviewer_notes_note_id_seq;

-- ============================================================
-- STEP 4: Rename indexes
-- ============================================================
ALTER INDEX IF EXISTS staging.idx_steward_notes_hnsw RENAME TO idx_reviewer_notes_hnsw;

-- ============================================================
-- STEP 5: Update table comments
-- ============================================================
COMMENT ON TABLE staging.decision_candidates IS 'Scored candidate decision pairs — generated via blocking + multi-attribute similarity';
COMMENT ON TABLE staging.reviewer_notes IS 'Reviewer resolution notes with 512-dim Voyage voyage-3-lite embeddings for RAG retrieval';

-- ============================================================
-- STEP 6: Verify
-- ============================================================
SELECT tablename FROM pg_tables WHERE schemaname = 'staging' ORDER BY tablename;
